Gizmos require depth stencil
```
cargo run --example 2d_gizmos
```

the example above will fail with

```
thread '<unnamed>' panicked at /Users/chris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.4/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 2, Metal)>`
    In a set_pipeline command
      note: render pipeline = `LineGizmo Pipeline 2D`
    Render pipeline targets are incompatible with render pass
    Incompatible depth-stencil attachment format: the RenderPass uses a texture with format Some(Depth32Float) but the RenderPipeline uses an attachment with format None
```

if the stencil is not included.

Additionally, the line joints can be modified using the keys in the example to cause a second crash, which also requires the depth stencil